### ISSUE TITLE
"taming" dependency not found

### ISSUE THREAD

**Issue by sidney1505** [lmb-freiburg/ldce#2]
Hi,

I tried executing the code base again, but get the following error:

"Traceback (most recent call last):
  File "/home/sidney/workspace/ldce/scripts/ldce.py", line 238, in main
    model = get_model(cfg_path=cfg.diffusion_model.cfg_path, ckpt_path = cfg.diffusion_model.ckpt_path).to(device).eval()
  File "/home/sidney/workspace/ldce/sampling_helpers.py", line 106, in get_model
    model = load_model_from_config(config, ckpt_path)
  File "/home/sidney/workspace/ldce/sampling_helpers.py", line 97, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/home/sidney/workspace/ldce/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/sidney/workspace/ldce/ldm/util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/opt/conda/envs/peal/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sidney/workspace/ldce/ldm/models/diffusion/ddpm.py", line 24, in <module>
    from ldm.models.autoencoder import VQModelInterface, IdentityFirstStage, AutoencoderKL
  File "/home/sidney/workspace/ldce/ldm/models/autoencoder.py", line 6, in <module>
    from taming.modules.vqvae.quantize import VectorQuantizer2 as VectorQuantizer
ModuleNotFoundError: No module named 'taming'
"

Is this refering to "https://pypi.org/project/taming-transformers"? I can't see it in the environment.yml.

Best,
Sidney

**Comment by SimonSchrodi** [comment]
Hi Sidney,

thanks for finding this! I've added the missing dependency in the environment.yml ([6519597](https://github.com/lmb-freiburg/ldce/commit/65195978cf84ac56a492fa4f93bc14e42d304cb3)).

Best,
Simon
